### ISSUE TITLE
why have not pose nms

### ISSUE THREAD

**Issue by RedFree** [LuongTanDat/AlphaPose-Cpp#1]
Hi, Why this implement has not pose_nms.

**Comment by datlt4** [comment]
@RedFree, when I debug [Alphapose code](https://github.com/MVIG-SJTU/AlphaPose/blob/master/alphapose/utils/pPose_nms.py#L222) and I found that, result from inference all image in my dataset are the same with code without nms. Each keypoint is the max number in each feature map, if that number less than a certain theshold, you should remove that keypoint. I wanted to get full output keypoints, so I did not add comparation step into my code. Because of the same result between `with nms` and `without nms`, i ignored that function in my C++ code. This repos was developed for [model FastPose Resnet50](https://github.com/MVIG-SJTU/AlphaPose/blob/master/configs/coco/resnet/256x192_res50_lr1e-3_1x.yaml) that have 17 keypoints from output model. So I also set all variable related to output size of model 17Kps
